---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet-clean-arch-gitops
  title: debug
  description: Template for Dotnet
  tags:
    - debug
spec:
  owner: sourabh.rustagi
  type: debug
  parameters:
    - title: Dotnet Solution/Project details
      required:
        - project_name # solution name
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component - will be used for Dotnet Solution file name
          ui:field: EntityNamePicker
          maxLength: 50
          pattern: '^[a-z0-9]+$'
  steps:
    - id: template
      name: Preparing Dotnet template
      action: dotnet:template:install
      input:
        package: Clean.Architecture.Solution.Template::8.0.0-preview.7.2
        args:
        - --force
    - id: template
      name: Preparing Dotnet new Clean Architecture Solution
      action: dotnet:new
      input:
        template: ca-sln
        args:
          - -cf
          - None
          - -o
          - ${{ parameter.project_name }}
          
